language: node_js
node_js: "8"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g typescript'
install:
  - 'npm install --ignore-scripts'
  - 'npm install'
  # https://github.com/travis-ci/travis-ci/issues/8813
  - 'rm -f ./node_modules/.bin/which'
script:
  - 'npm test --silent'
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then
    mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization="camel-tooling" -Dsonar.projectKey="generator-camel-project" -Dsonar.projectName="Camel Project Generator"; 
    fi
cache:
  directories:
    - "node_modules"
env: DISPLAY=:99
addons:
  sonarcloud:
    organization: "camel-tooling"
    branches:
      - master
